### ISSUE TITLE
WebPA Data Model

### ISSUE THREAD

**Issue by spvickers** [WebPA/Docs#2]
I think it would be great to have the WebPA data model diagram added to this repository.  I am not sure whether it is available from elsewhere, but the latest one I can find is attached.  (I also have the Visio source file if anyone is interested.)  Thanks.

[WebPA2_0_0_6.pdf](https://github.com/WebPA/Docs/files/2072992/WebPA2_0_0_6.pdf)

**Comment by Sephster** [comment]
Sounds like a good idea @spvickers as it should help devs get the system set up and extend it if need be. Do you know if it is still accurate? From the file name it looks like it was for 2.0.0.6 but I suspect little has changed between that an 2.0.0.11

**Comment by spvickers** [comment]
I am not aware of any database changes made since that time.  I have not seen any documentation to advise on upgrading from 2.0.0.6 to later versions which required database changes.

**Comment by Sephster** [comment]
Thanks. I think I can get this merged in to the root of the dir with the other PDF files although we should probably change the file name to be something more descriptive and keep in line with the naming conventions used by the other docs. If you want to create a PR I'd be happy to get this added in. If not, I can do this tomorrow. Thanks @spvickers

**Comment by spvickers** [comment]
I tried to create a pull request before submitting this issue but could see how to do so without creating my own fork of this repository which I preferred not to do just for this simple change.  This repository did not allow me to upload a file without having push access.  Let me know if there was another way I could have done this.

**Comment by Sephster** [comment]
I think the only way you can is to fork the repo. No problem, I will do this tomorrow on your behalf so we can get it merged in. Thanks Stephen.

**Comment by Sephster** [comment]
I've added this document in now. Thanks @spvickers
